-- CONFIG FOR PLUGINS
-- Ranger for neovim (rnvimr)
-- vim.g.rnvimr_enable_ex = 1
-- vim.g.rnvimr_enable_picker = 1
-- vim.g.rnvimr_edit_cmd = 'drop'
-- vim.g.rnvimr_draw_border = 0
-- vim.g.rnvimr_border_attr = {'fg': 14, 'bg': -1}
-- vim.g.rnvimr_shadow_winblend = 70
-- vim.g.rnvimr_ranger_cmd = ['ranger', '--cmd=set draw_borders both']
-- vim.cmd('highlight link RnvimrNormal CursorLine')
-- vim.cmd('nmap <space>r :RnvimrToggle<CR>')
-- vim.cmd('nmap <space>f :Telescope find_files<CR>')
-- vim.cmd('nmap <space>g :Telescope live_grep<CR>')
